### ISSUE TITLE
PpSsPp Go on Rgb10 Max 

### ISSUE THREAD

**Issue by Tenchirox** [southoz/RetroOZ#12]
Hi, 
Even with last 0.50 beta from July 17 ppsspp go mapping is off on powkiddy rgb10 max, select/start and down/up are exchanged (pushing up is start) and there is no way to access to the emulator menu even with an usb keyboard.

**Comment by southoz** [comment]
Thanks, Menu is Select + X, Native is Key Marked "Select" and "X" https://github.com/southoz/RetroOZ/wiki/PSP#hotkeys-in-combination-with-14-select while Top Profile is Button next to the DPAD and "X" https://github.com/southoz/RetroOZ/wiki/PSP#hotkeys-in-combination-with-12-select-2 this is the same as Retroarch and Retoarch32. Check the Wiki Page and double check the key combination you are using. I will hold the ticket open just encase I am missing something.

**Comment by Tenchirox** [comment]
Actually for me on ppsspp go (not ppsspp sdl (standalone) this one work fine) dpad up is start, dpad down is select...
https://youtu.be/lTCUqK64onU

**Comment by southoz** [comment]
Can you try with the latest update, I have moved the ppsspp folder to /roms/psp so permissions are not an issue with the config files. Make sure you apply the device profile.

**Comment by Tenchirox** [comment]
So it kinda work, if a game was launch for the first time or as long you don't change setting for it  after update it work, if the game have a previously edited config in the other end it continue to beave the same way, need to delete per game config in \roms\psp\ppsspp\PSP\SYSTEM and after that everything seem ok

**Comment by southoz** [comment]
Plaidman - SDL version seems to be fine. interestingly, the button IDs are different between GO and SDL. in both, with default settings, L and R are mapped to b6 and b5 respectively. in SDL, this works fine, but in GO they should be mapped to b7 and b8
