### ISSUE TITLE
Permanently change retroarch settings

### ISSUE THREAD

**Issue by pglira** [southoz/RetroOZ#23]
I like to set "Auto save state" and "Load State Automatically" to ON in retroarch. It seems that if I set these options during gaming, they are not remembered when I start the game the next time. Is there a way to set these two options permanently?

BTW, thank you for your great work!

**Comment by southoz** [comment]
Hi, you can:
1. save either a Core / Content Directory / Game override using the Override menu in the quick menu.
2. make the change globally and save the change to retroarch.cfg by manually going to Main Menu -> Configuration File -> Save Current Config.

**Comment by pglira** [comment]
Thank you, it worked perfectly!
