### ISSUE TITLE
All ports games are weird.

### ISSUE THREAD

**Issue by dj5927** [southoz/RetroOZ#29]
All ports games are weird.
Undertale not working
(Files that run well with other firmware)
arkos
The same file runs fine in arkos.

Cave Story - Compiled with evo 60fps doesn't work
(Files that run well with other firmware)

All other port games feel like 30fps scrolling.
It is not soft.
All ports in retrooz have problems.

Comparing the same game with other firmware
The scrolling is very rough and feels choppy.

**Comment by southoz** [comment]
Feel Free to Jump in and help, you are up against 854x480 screen resolution compared to 480x320, broken drivers and an SDL implementation without video support.

Please try to be constructive not complain about free software, report each issue as a single ticket and Undertale is working as at 11 Aug Beta Release.
