### ISSUE TITLE
About the RGB10Max2 joystick using RetroOZ

### ISSUE THREAD

**Issue by gtseriesx** [southoz/RetroOZ#47]
hi, I burn the RetroOZ image（0.51 16GB version) to the tf card, and put it onto RGB10MAX2, the dual joystick is reversed. How can I fix it~ thankyou~

**Comment by southoz** [comment]
RGB10MAX2 Support is added in 0.52b  - https://forum.odroid.com/viewtopic.php?p=339901#p339901
