### ISSUE TITLE
powkiddy rgb10 max 2 inverse analog sticks

### ISSUE THREAD

**Issue by JohnEnderas** [southoz/RetroOZ#50]
On the powkiddy rgb10 max 2, the analog sticks are inverse, right is left and down is up

**Comment by southoz** [comment]
please install the latest Beta as it should resolve the issue, I don't have a MAX2 to test with so it's over to the community to validate. https://forum.odroid.com/viewtopic.php?p=342512&sid=9459f2bbda80dd7ab8b88da9290ebb42#p342512
