### ISSUE TITLE
Rom folder spelling error: pcenginecd

### ISSUE THREAD

**Issue by kshark8** [southoz/RetroOZ#51]
Notice there is a spelling error in the rom folder for PC Engine CD. 
Not sure if it's intended, but it is currently spelled as pceneginecd.

RetroOZ Version (0.51)

**Comment by southoz** [comment]
There is a fix in the 0.52beta script

`mv /roms/pceneginecd /roms/pcenginecd`

**Comment by kshark8** [comment]
Oh cool, I see. I updated the beta after changing the folder name. So I didn't notice. Thanks for letting me know. i will resolve the case.
