### ISSUE TITLE
Mame Core issue

### ISSUE THREAD

**Issue by jubairsky** [southoz/RetroOZ#55]
![IMG_20220224_234806](https://user-images.githubusercontent.com/71275850/155579281-2ce29aff-858b-4e7c-a7b0-fe21327c66f1.jpg)

Sir
How to change Mame core? I cant find option here for Mame game, but I can play some game of my collection from real SD Card on Emuelec. RGB10Max.
Please see attracted image for better view.

**Comment by southoz** [comment]
The mame core is hard mapped in /etc/emulationstation/es_systems.cfg it in the Arcade section up the top of the file, typically I would use sudo mc and edit with F4 (nano) or sudo nano /etc/emulationstation/es_systems.cfg - Custom es_system.cfg changes will be overwritten during updates so make sure you back up your changes in a text file.

**Comment by jubairsky** [comment]
that is hard way when I have no linux PC. Please make available core option in emulator setting next update.

**Comment by southoz** [comment]
The Directories are hard set to mame2003 (Mame 2003 Plus) and mame2010 being the MAME cores that are supported with acceptable performance. 

arcade cps1 cps 2 cps3 are the flexible folders being able to swap between:

- FBNEO
- FBAlpha 2012
- Mame 2003 Plus
- Mame 2010
- FBAlpha 2012 (32bit)
- FBAlpha 2016 (32bit)
- Mame 2003 Extreme  (32bit)

**Comment by jubairsky** [comment]
it also hard way to find out rom version, I have single set of Mame rom collection, how to rearrange by different folder? its not easy for beginner user. So, please make option for single mame Roms as emuelec or batocera, they have option per game emulator change.
Thanks

**Comment by southoz** [comment]
If you don't know your ROM version then you need to use clrmamepro or download a romset that is specific to a version of mame.

The folders and core support are based on ArkOS and it will remain in Sync with that distro - see https://github.com/christianhaitian/arkos/wiki/ArkOS-Emulators-and-Ports-information for details.
