### ISSUE TITLE
OneDrive link: "This item might not exist or is no longer available"

### ISSUE THREAD

**Issue by pmbarros** [southoz/RetroOZ#57]
The OneDrive link to the current image leads to an error page that says "This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information."

**Comment by southoz** [comment]
thanks I have updated the link to https://1drv.ms/u/s!Ag5nl1V4mxXqhMYG6AxEpO9lIw_5gQ?e=IxreTf
